main: "com.mrjoshuasperry.creeperworks.Main"
name: "Creeperworks"
version: ${project.version}
authors: ["mrsperry"]
description: "Adds a colorful firework to creeper explosions"
api-version: "1.21"
