# All modules are enabled by default. To disable a module, add `enabled: false` to its section.

autobreeding:
  # Delay is in seconds
  min-delay: 0.25
  max-delay: 2
  range: 10

beeplanter:
  search-radius: 4

biomebombs:
  bomb-range: 9
  crafting-output: 4

chat:
  # Seperates the name from the message. A space is added after the delimiter, but not before
  message-delimiter: " »"
  # Any of these colors can be hex strings or named colors (e.g. "red", "blue")
  delimiter-color: "#cccccc"
  message-color: "#ededed"
  # This color represents when the console uses /say
  console-color: "red"
  # This color represents when a player highlights their coordinates or items
  highlight-color: "aqua"

cobblegenerator:
  # These chances are a weighted ratio
  blocks:
    cobblestone: 1
    stone: 1

concretemixer:
  # Use change is out of 100
  water-use-chance: 5

dyeshears:
  # Dye change is out of 100
  dye-chance: 50

featherplucker:
  # Cooldown is in seconds
  cooldown: 300

igneousgenerator:
  # Conversion time is in seconds
  max-conversion-time: 2

mobgriefing:
  no-sheep-griefing: true
  no-enderman-griefing: true

mobsizes:
  # 1.0 is default size
  min-size: 0.85
  max-size: 1.15
  # This will size ridable mounts based on their HP pool rather than randomly
  enable-mount-health-sizing: true

name-colors:
  default-name-color: "#6b6bff"

nameping:
  # Ping cooldown is in seconds
  ping-cooldown: 5

woodpile:
  # How many seconds it takes to convert a single log
  log-convert-time: 5
