main: com.mrjoshuasperry.pocketplugins.PocketPlugins
name: PocketPlugins
version: ${project.version}
description: A collection of small changes and additions to enhance vanilla gameplay
authors:
  - mrsperry
  - TimPCunningham
api-version: "1.21"
commands:
  markers:
    description: Manage your map markers
    usage: /markers <add | list>
  biomebombs:
    description: Lists all available biome bombs and their crafting ingredients
    usage: /biomebombs
    aliases: [bb]
  macro:
    description: Command macro management
    usage: /macro <list | run>
