main: com.mrjoshuasperry.pocketplugins.PocketPlugins
name: PocketPlugins
version: ${project.version}
description: A collection of small changes and additions to enhance vanilla gameplay
authors:
  - mrsperry
  - TimPCunningham
api-version: "1.21"
permissions:
  pocketplugins.macros.op:
    description: Allows running and viewing command macros flagged op-only
    default: op
