main: com.mrjoshuasperry.pocketplugins.PocketPlugins
name: PocketPlugins
version: ${project.version}
description: Adds small additions to minecraft
authors:
  - "mrsperry"
  - "TimPCunningham"
api-version: "1.21"
commands:
  synth:
    description: A tool for making a sound effect
    usage: /synth [add|remove|edit|list|play]
  shoot:
    description: Shoots a glass bottle
    usage: /shoot
