recipes:
  shaped-recipe:
    recipe-type: "shaped"
    output-name: "{dark_aqua} Player Core"
    output-lore:
      - "{gold} A mysterious essence of a player"
      - "{gold} Could be used in crafting..."
    output-enchantments:
      - "damage_all:5"
    output-material: "emerald"
    output-amount: 1
    input-shape:
      - " l "
      - "lel"
      - " l "
    input-reference:
      l: "ink_sack:4"
      e: "emerald"
  shapeless-recipe:
    recipe-type: "shapeless"
    output-material: "packed_ice"
    output-amount: 1
    input-materials:
      - "4 ice"