main: "com.mrjoshuasperry.croptweaks.Main"
name: "CropTweaks"
version: ${project.version}
authors: ["mrsperry"]
description: "Allows the automatic harvesting and replanting of crops by right clicking them with a hoe, at the cost of all seeds."
api-version: "1.21"
