main: "com.mrjoshuasperry.autostack.Main"
name: "AutoStack"
version: ${project.version}
authors: ["mrsperry"]
description: "Automatically gives you an extra stack of items if you run out."
api-version: "1.21"
